### ISSUE TITLE
Unable to Download Files in Midori Android

### ISSUE THREAD

**Issue by kamrulhasanio** [goastian/midori-android#2]
I am currently using Midori Android as my default browser, and I have encountered an issue where I am unable to download any files. When I try to download a file, the download does not start, or it fails. This is a critical functionality that I rely on for my daily tasks, and it's not working as expected.

Device Information:
- Android Version: 8.1 and 13
- Midori Android Version: 3.0.07

I kindly request the developers to investigate and resolve this issue as it significantly impacts the usability of the browser for me. If any additional information or testing is needed, please let me know, and I'll be happy to assist.

Thank you for your attention to this matter.

**Comment by Ponchale** [comment]
We hope to solve this and other problems very soon, we already have an alpha version

**Comment by Ponchale** [comment]
This problem is resolved in version 3.5.1
